"""initial_tracks_playlist_playback_state

Revision ID: 934cd24cd9b0
Revises: 
Create Date: 2026-03-02 16:43:23.110706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934cd24cd9b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('filepath', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('artist', sa.String(length=512), nullable=True),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_filename'), 'tracks', ['filename'], unique=True)
    op.create_table('playback_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('current_track_id', sa.Integer(), nullable=True),
    sa.Column('is_playing', sa.Boolean(), nullable=False),
    sa.Column('position_seconds', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_order')
    op.drop_table('playback_state')
    op.drop_index(op.f('ix_tracks_filename'), table_name='tracks')
    op.drop_table('tracks')
    # ### end Alembic commands ###
